apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
<<<<<<< HEAD
version: 6.3.0
=======
<<<<<<< HEAD
version: 6.2.16
=======
version: 6.3.0
>>>>>>> c457c9d (changing version)
>>>>>>> 1f1cb5a (changing version)
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: retool-temporal-services-helm
    version: 1.1.5
    condition: retool-temporal-services-helm.enabled,workflows.enabled
